### ISSUE TITLE
Angular 17 support

### ISSUE THREAD

**Issue by nevi-me** [david-ui-org/david-ui-angular#15]
**Is your feature request related to a problem? Please describe.**
Would you be able to update the library to support Angular 17? Alternatively, are you fine with accepting a contribution to support Angular 17?

**Describe the solution you'd like**
Supporting ng 17

**Describe alternatives you've considered**
Using ng 16, however ng 17 has interesting new features. I could also override the peer dependency requirements if possible.

**Additional context**
Trying to install the package in a new angular 17 project results in npm failing due to peer dependency issues.

**Comment by BinaryGeometry** [comment]
I found that when using standalone mode I needed to add the following to app.config.ts

```ts
import { provideAnimations } from "@angular/platform-browser/animations";
export const appConfig: ApplicationConfig = {
  providers: [provideRouter(routes), provideClientHydration(), provideAnimations()]
};
```
